//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.18 at 03:28:22 PM MSK 
//


package com.geekbrains.shop.api.order;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "orderInfo", propOrder = {
    "id",
    "created",
    "username",
    "sum",
    "amount",
    "status"
})
public class OrderInfo {

    protected long id;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar created;
    @XmlElement(required = true)
    protected String username;
    protected double sum;
    protected long amount;
    @XmlElement(required = true)
    protected String status;

    public long getId() {
        return id;
    }

   
    public void setId(long value) {
        this.id = value;
    }

    
    public XMLGregorianCalendar getCreated() {
        return created;
    }

   
    public void setCreated(XMLGregorianCalendar value) {
        this.created = value;
    }

   
    public String getUsername() {
        return username;
    }

   
    public void setUsername(String value) {
        this.username = value;
    }

   
    public double getSum() {
        return sum;
    }

   
    public void setSum(double value) {
        this.sum = value;
    }

   
    public long getAmount() {
        return amount;
    }

   
    public void setAmount(long value) {
        this.amount = value;
    }

    
    public String getStatus() {
        return status;
    }

    
    public void setStatus(String value) {
        this.status = value;
    }

}
