//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.18 at 03:28:22 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com/geekbrains/shop/api/order", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.geekbrains.shop.api.order;
